server:
  port: 8790
  tomcat:
    threads:
      max: 1000
      min-spare: 100
    accept-count: 1000
    max-connections: 10000
    accesslog:
      directory: /app/logs/access
  servlet:
    context-path: /
    session:
      cookie:
        name: OAUTH2SESSION
        path: /
      timeout: 10800
spring:
  profiles:
    active: uat
  application:
    name: agent-x-expand
    cnName: 智川扩展服务
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    # 漏洞修复
    cors:
      # 若不需要跨域，直接关闭 CORS 配置
      enabled: true
      # 如需跨域，按需配置（⚠️生产环境慎用）
      allowed-origins:
        - https://trusted-site.com
        - http://localhost:8080
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
      allowed-headers:
        - Content-Type
        - Authorization
      # 避免设置过长的缓存时间（单位：秒）
      max-age: 1800
      # 明确禁用以下高危配置
      allow-credentials: false
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  redis:
    jedis:
      pool:
        max-wait: -1ms #连接池最大阻塞等待时间 使用负值表示没有限制
        max-active: 4  #连接池最大连接数 使用负值表示没有限制
        min-idle: 0    #连接池中最小空闲连接
        max-idle: 4    #连接池中最大空闲连接
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    password: xxxxx
    host: xxxxx
    port: xxxxx

appframe:
  # 开启公共模块
  common:
    enable: true
  page:
    # 开启分页控制
    enable: true
    # pagesize最大值
    maxPageSize: 201
    # 忽略最大值限制的api
    maxPageSizeIgnoreApi: getApplicationInfoList
  log:
    # 是否开启日志打印，如果字段是文件或则其他特殊类型，标记为不转json，	@JSONField(serialize = false)
    enable: true
    # 是否开启入参打印
    paramEnable: true
    # 用户名key，当有用户时，需要指定一个用户字段，默认为userId，打印日志中会显示用户信息
    userKey: accountName
    # 返回打印
    resultEnable: true
    ignore: uploadPackage,upload,uploadBatch,ignores,heartbeat,logs,logss
  vulnerability:
    enable: false
    interceptorUrl: /webjars/**,/v2/**,/v3/**
  cipher:
    enable: false
    md5Key: xxxxxxx
    whiterApi: /cicd/**,/dialogue/**,/wos/file/**
    timeout: 2000
  graylog:
    enable: false
    host: xxxxxxx
    port: xxxxxxx
  jasypt:
    enable: true
    salt: xxxxxxx
    encryptor:
      algorithm: PBEWITHHMACSHA512ANDAES_256
      password: xxxxxxx=
  limit:
    enable: true
    count: 50
    period: 2
    prefix: agent-x-uat
  minio:
    enable: true
    # minio的服务地址
    endpoint: xxxxxxx
    # minio的登录账号
    accessKey: xxxxxxx
    # minio的登录密码
    secretKey: xxxxxxx
    bucket: smart-agent-uat
    gateway: xxxxxxx

mybatis:
  mapper-locations: classpath*:/mappers/*.xml

mybatis-flex:
  logicDelete:
    # 逻辑删除，有效数据，默认为0
    normalValue: 0
    # 逻辑删除，无效数据，默认1
    deletedValue: 1
    # SQL 审计
  auditEnable: false
  datasource:
    myds:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: xxxxxxx
      username: xxxxxxx
      password: xxxxxxx
logging:
  config: classpath:logback-core.xml
  level:
    com.wenge.expand.mapper: DEBUG

# 多媒体
multimedia:
  video:
    downloadPath: /app/videoTemp