<template>
    <div class="generate-page">
        <div class="left-container">
            <div class="left-header">
                <div style="padding: 8px;">
                    <el-icon size="16" color="#1D2129">
                        <Fold />
                    </el-icon>
                </div>
            </div>
            <div class="left-mian">
                <div class="left-mian-item" :class="{ 'selected': selectedIndex === index }"
                    v-for="(item, index) in taskSplit" :key="index" @click="selectItem(item, index)">
                    <img src="../../../assets/img/icon_book.png" alt="">
                    <p class="truncate-text">{{ item.content }}</p>
                </div>
            </div>
        </div>
        <div class="right-container">
            <div class="right-header">
                <div class="right-header-left">
                    <img src="../../../assets/img/icon_book.png" alt="">
                    <p>{{ selectedItem.content }}</p>
                </div>
                <div class="right-save" @click="exportWord">
                    <img src="../../../assets/img/save-line.png" alt="">
                </div>
            </div>
            <div class="right-mian" v-html="parsedMarkdown">
                
            </div>
        </div>
    </div>
</template>

<script lang="ts" setup>
import { ref, defineProps, computed } from 'vue';
import { ElIcon, ElMessage } from 'element-plus';
import { Fold } from '@element-plus/icons-vue';
import { marked } from 'marked';
import { Document, Paragraph, TextRun, HeadingLevel, Packer } from 'docx';
import { saveAs } from 'file-saver';

const props = defineProps({
    taskSplit: {
        type: Array,
        required: true,
        default: () => []
    },
});

// 默认选中第一个
const selectedIndex = ref(0);
// 选中的文档
const selectedItem = ref(props.taskSplit[selectedIndex.value]);

const parsedMarkdown = computed(() => {
    return marked(selectedItem.value.answer);
});

// 选中对应的文档
const selectItem = (item, index) => {
    selectedIndex.value = index;
    selectedItem.value = item;
}

// 导出成word
const exportWord = async () => {
    try {
        // 创建一个新的文档对象
        const doc = new Document({
            title: selectedItem.value.content,
            description: "Generated by AI Assistant",
            styles: {
                paragraphStyles: [
                    {
                        id: "normal",
                        name: "Normal",
                        run: {
                            size: 24, // 12pt
                            font: "Calibri",
                        },
                        paragraph: {
                            spacing: {
                                line: 276, // 1.15 line spacing
                            },
                        },
                    },
                ],
            },
            sections: [
                {
                    properties: {},
                    children: await convertHtmlToDocx(parsedMarkdown.value),
                },
            ],
        });

        // 生成Blob并下载
        Packer.toBlob(doc).then((blob) => {
            saveAs(blob, `${selectedItem.value.content}.docx`);
            ElMessage.success('导出Word成功');
        });
    } catch (error) {
        console.error('导出Word失败:', error);
        ElMessage.error('导出Word失败');
    }
}

// 将HTML转换为docx格式
const convertHtmlToDocx = async (htmlString: string) => {
    // 创建一个虚拟DOM来解析HTML
    const parser = new DOMParser();
    const doc = parser.parseFromString(htmlString, 'text/html');
    
    // 递归处理DOM节点
    const processNode = (node: Node): any[] => {
        const result = [];
        
        // 处理文本节点
        if (node.nodeType === Node.TEXT_NODE) {
            const text = node.textContent?.trim();
            if (text) {
                result.push(
                    new TextRun({
                        text: text,
                    })
                );
            }
            return result;
        }
        
        // 处理元素节点
        if (node.nodeType === Node.ELEMENT_NODE) {
            const element = node as HTMLElement;
            
            // 处理段落
            if (element.tagName === 'P') {
                const children = [];
                for (const child of Array.from(element.childNodes)) {
                    children.push(...processNode(child));
                }
                result.push(new Paragraph({ children }));
            }
            // 处理标题
            else if (/^H[1-6]$/.test(element.tagName)) {
                const level = parseInt(element.tagName.substring(1)) as HeadingLevel;
                const children = [];
                for (const child of Array.from(element.childNodes)) {
                    children.push(...processNode(child));
                }
                result.push(new Paragraph({
                    heading: level,
                    children,
                }));
            }
            // 处理加粗文本
            else if (element.tagName === 'STRONG' || element.tagName === 'B') {
                const children = [];
                for (const child of Array.from(element.childNodes)) {
                    children.push(...processNode(child));
                }
                result.push(new TextRun({
                    bold: true,
                    children,
                }));
            }
            // 处理斜体文本
            else if (element.tagName === 'EM' || element.tagName === 'I') {
                const children = [];
                for (const child of Array.from(element.childNodes)) {
                    children.push(...processNode(child));
                }
                result.push(new TextRun({
                    italics: true,
                    children,
                }));
            }
            // 处理下划线文本
            else if (element.tagName === 'U') {
                const children = [];
                for (const child of Array.from(element.childNodes)) {
                    children.push(...processNode(child));
                }
                result.push(new TextRun({
                    underline: {},
                    children,
                }));
            }
            // 处理列表
            else if (element.tagName === 'UL' || element.tagName === 'OL') {
                for (const li of Array.from(element.querySelectorAll('li'))) {
                    const children = [];
                    for (const child of Array.from(li.childNodes)) {
                        children.push(...processNode(child));
                    }
                    result.push(new Paragraph({
                        bullet: { level: 0 },
                        children,
                    }));
                }
            }
            // 处理换行
            else if (element.tagName === 'BR') {
                result.push(new TextRun({
                    text: '',
                    break: 1,
                }));
            }
            // 处理其他元素
            else {
                for (const child of Array.from(element.childNodes)) {
                    result.push(...processNode(child));
                }
            }
        }
        
        return result;
    };
    
    // 处理body下的所有子节点
    const children = [];
    for (const child of Array.from(doc.body.childNodes)) {
        children.push(...processNode(child));
    }
    
    return children;
}
</script>

<style scoped lang="scss">
.generate-page {
    box-sizing: border-box;
    display: flex;

    .left-container {
        box-sizing: border-box;
        width: 298px;
        height: 756px;
        border-right: 1px solid #E7E7E7;
        // padding: 8px;

        .left-header {
            // width: 248px;
            height: 48px;
            border-bottom: 1px solid #E7E7E7;
            display: flex;
            align-items: center;
        }

        .left-mian {

            .selected {
                background-color: #D0DFFD;
            }

            .left-mian-item {
                font-weight: 400;
                font-size: 14px;
                color: #1D2129;
                display: flex;
                align-items: center;
                padding: 10px 16px;
                cursor: pointer;

                img {
                    width: 20px;
                    height: 20px;
                    margin-right: 8px;
                }

                .truncate-text {
                    white-space: nowrap;
                    overflow: hidden;
                    text-overflow: ellipsis;
                    max-width: 100%;
                }

            }
        }
    }

    .right-container {
        box-sizing: border-box;
        width: 100%;

        .right-header {
            width: 100%;
            height: 48px;
            border-bottom: 1px solid #E7E7E7;
            display: flex;
            justify-content: space-between;
            align-items: center;

            .right-header-left {
                display: flex;
                align-items: center;
                font-weight: 400;
                font-size: 14px;
                color: #1D2129;

                img {
                    width: 24px;
                    height: 24px;
                    margin-left: 16px;
                    margin-right: 8px;
                }
            }

            .right-save {
                margin-right: 16px;
                width: 20px;
                height: 20px;
                cursor: pointer;

                img {
                    width: 100%;
                    height: 100%;
                }
            }
        }
    }

    .right-mian {
        padding: 26px 30px;
        max-height: 700px;
        overflow-y: auto;
        font-family: MiSans, MiSans;
        letter-spacing: 1px;
    }

    .right-main::-webkit-scrollbar {
        display: none;
    }
}
</style>